name: wia_prayer_app
description: "Windsor Islamic Association - Prayer times, Qibla compass, and notifications for the Muslim community in Windsor."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  hijri: ^3.0.0
  sensors_plus: ^4.0.2
  awesome_notifications: ^0.10.1
  url_launcher: ^6.2.2
  flutter_compass: ^0.8.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  geocoding: ^2.1.1
  # Widget support for home screen widgets
  home_widget: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/prayer_times.json